- name: install cldemo apt-key
  apt_key: url=http://cldemo.cumulusnetworks.com/stable/dists/cldemo/cldemo.key

- name: add cldemo sources list
  copy: src=cldemo.list dest=/etc/apt/sources.list.d/cldemo.list

- name: add brightbox and ansible ppa
  apt_repository:  repo={{item}}
  with_items:
    - ppa:brightbox/ruby-ng
    - ppa:ansible/ansible

- name: copy deb that enables puppet repo to host
  copy: src=puppetlabs-release-trusty.deb dest=/tmp/puppet_install.deb

- name: install puppet repo deb
  apt: deb=/tmp/puppet_install.deb

- name: run apt-get update
  apt: update_cache=yes

- name: install cldemo base packages
  apt: name={{ item }}
  with_items:
    - ruby2.1
    - bundler
    - cldemo-wbench-base
    - git

- name: copy ansible user authorized_keys to cumulus user ssh authorized_keys. needed for prepare_cumulus_env role
  command: cp {{ ansible_env.PWD }}/.ssh/authorized_keys /home/cumulus/.ssh/authorized_keys

- name: create dummy files so that cldemo installs
  file: path=/var/www/{{item}} state=touch
  with_items:
    - topology.dot
    - dummy.lic
    - wbench.json
