- name: run apt-get update
  apt: update_cache=yes

- name: install service packages
  apt: name={{item}} state=present
  with_items:
    - ntp
    - isc-dhcp-server

- name: configure ntp
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: configure dhcpd.conf
  template: src=dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf
  notify: restart dhcp

- name: configure dhcpd.pool
  template: src=dhcpd.pools.j2 dest=/etc/dhcp/dhcpd.pools
  notify: restart dhcp

- name: touch dhcpd.hosts file. Not clear how this will be managed
  file: path=/etc/dhcp/dhcpd.hosts state=touch
