- name: create cumulus user. Passwd is cn321
  user: name="{{wbench_user}}"
        password="{{wbench_passwd}}"
        update_password=on_create
        generate_ssh_key=yes
        shell='/bin/bash'

- name: set wbench user user ability to run sudo with a passwd
  copy: content="{{wbench_user}} ALL=(ALL) NOPASSWD:ALL"
        dest="/etc/sudoers.d/10_{{wbench_user}}"
        validate="/usr/sbin/visudo -cf %s"
        mode=0440

- name: remove ubuntu user if it exists
  user: name=ubuntu state=absent

- name: generate ssh keys for ansible user (most likely root)
  user: name={{ ansible_user_id}} generate_ssh_key=yes
