- name: install cldemo-tests as cumulus user
  git: repo=https://github.com/CumulusNetworks/cldemo-tests dest=/home/cumulus/cldemo-tests

- name: bundle install in cldemo-tests directory
  command: bundle install --without=test
  args:
      chdir: /home/cumulus/cldemo-tests

- name: chown to cumulus/cumulus
  file: path=/home/cumulus/cldemo-tests state=directory recurse=yes owner=cumulus group=cumulus
