# list extra packages here
- name: install useful user packages
  apt: name={{item}}
  sudo: yes
  with_items:
    - vim-nox
    - tree
    - nano
    - git
    - telnet

- name: Download ccw wbenchvm tools
  git: repo=https://github.com/cumulusnetworks/ccw-wbenchvm-tools.git dest=/usr/src/ccw-wbenchvm-tools

- name: symlink the cwng scripts
  file: src={{ item }} dest=/usr/local/bin/{{item | basename}} state=link
  with_lines: ls /usr/src/ccw-wbenchvm-tools/cwng-*
