# list extra packages here
- name: install useful user packages
  apt: name={{item}}
  sudo: yes
  with_items:
    - vim-nox
    - tree
    - nano
    - git
    - telnet
    - sshpass

- name: Download ccw wbenchvm tools
  git: repo=https://github.com/cumulusnetworks/ccw-wbenchvm-tools.git dest=/usr/src/ccw-wbenchvm-tools

- name: symlink the cwng scripts
  file: src=/usr/src/ccw-wbenchvm-tools/{{ item }} dest=/usr/local/bin/{{item}} state=link
  with_items:
    - cwng-swpower
    - cwng-pxehelper
