" only run pathogen plugins if pathogen exists
if filereadable(expand("~/.vim/autoload/pathogen.vim"))
  call pathogen#infect()
  call pathogen#helptags()
  set statusline+=%#warningmsg#
  set statusline+=%{SyntasticStatuslineFlag()}
  set statusline+=%*

  let g:syntastic_always_populate_loc_list = 1
  let g:syntastic_auto_loc_list = 1
  let g:syntastic_check_on_open = 1
  let g:syntastic_check_on_wq = 0

  map <Leader>n <plug>NERDTreeTabsToggle<CR>
endif

syntax on
filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab
set textwidth=85


